################################# Default configuration ###################
baseURL = "https://fossrit.github.io/knowledgebase/"
title = "Open@RIT Knowledgebase"
theme = "dot"
enableEmoji = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true


################################# Navigation ################################
[[menu.main]]
weight = 10
name = "FAQ"
url = "faq"

[[menu.main]]
weight = 20
name = "pages"
url = "pages"
hasChildren = true

    [[menu.main]]
    parent = "pages"
    name = "Creative Commons"
    url = "cc"
    weight = 10

    [[menu.main]]
    parent = "pages"
    name = "Free/Open Source Software"
    url = "foss"
    weight = 20

    [[menu.main]]
    parent = "pages"
    name = "Open Data"
    url = "open-data"
    weight = 30

    [[menu.main]]
    parent = "pages"
    name = "Open Educational Resources (OERs)"
    url = "oers"
    weight = 40

    [[menu.main]]
    parent = "pages"
    name = "Workshops"
    url = "workshops"
    weight = 50


############################# Default parameters ##########################
[params]
logo = "images/rit.png"

# customize color
primary_color = "#F76902"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family (choose from https://fonts.google.com/)
font_family = "Public+Sans"

# contact form action (works with https://formspree.io)
contact_form_action = "#"


############################## Social links ##############################
# themify icon pack : https://themify.me/themify-icons

[[params.social]]
icon = "ti-github"
link = "https://github.com/FOSSRIT"

[[params.social]]
icon = "ti-comment-alt"
link = "https://telegram.me/fossrit"


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Creative Commons BY-SA 4.0"

# banner
[Languages.en.params.banner]
title = "Open@RIT Knowledgebase"
subtitle = "Knowledgebase for Open@RIT Workshops and Resources on how to work open"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Search our resources"
